name: integration-tests

run-name: integration-checks
on:
    pull_request:
        paths:
            - '**/*'

jobs:
    go-integration-checks:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout github actions
                uses: actions/checkout@v4
            
            -   name: Setup go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.21.0'

            -   name: Install go
                run: go version
                
            -   name: Install postgres
                run: |
                    sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
                    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
                    sudo apt-get update
                    sudo apt-get install postgresql-12 postgresql-client-12

            -   name: Start PostgreSQL
                run: sudo systemctl start postgresql

            -   name: Change PostgresSQL password
                run: |
                    sudo su postgres -c "psql --command=\"ALTER USER postgres WITH PASSWORD 'password';\""

            -   name: Create Users file
                run: bash ./.github/workflows/create-users.sh

            -   name: Create test environment variables
                run: bash ./.github/workflows/test-env-vars.sh

            -   name: Run integration tests
                run: |
                    go test ./tests/integration/